# -*- coding: utf-8 -*-
"""ai_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlFzcWghyUrYPcgjryJ7Q0YtsbrdpJsB
"""

import numpy as np
import tensorflow as tf
import google.generativeai as genai

# 1. Konfigurasi Model dan API
MODEL_PATH = 'career_recsys_model_custom.keras'
GEMINI_API_KEY = 'AIzaSyAnMK3t7-uLeaUWidS6SnTgeKLv_xmmb8Y' # Backend dev akan memasukkan ini via .env

try:
    # Memuat model Deep Learning yang sudah dilatih
    recsys_model = tf.keras.models.load_model(MODEL_PATH)
except Exception as e:
    print(f"Error loading model: {e}")

genai.configure(api_key=GEMINI_API_KEY)
gemini_model = genai.GenerativeModel('gemini-1.5-flash-latest')

# Daftar urutan label karir (Harus sama persis dengan urutan saat training)
CAREER_LABELS = [
    'Backend Developer', 'Cloud Engineer', 'Cybersecurity Analyst',
    'Data Analyst', 'Data Engineer', 'Data Scientist',
    'Database Administrator (DBA)', 'DevOps Engineer', 'Frontend Developer',
    'Full Stack Developer', 'Game Developer', 'IT Support Specialist',
    'Machine Learning Engineer', 'Mobile App Developer',
    'Product Manager (Teknologi)', 'QA Engineer', 'System Administrator',
    'UX Designer'
]

def generate_roadmap(predicted_career, user_skills, user_tools):
    prompt = f"""
    Kamu adalah seorang AI Career Coach senior yang ahli di industri Teknologi Informasi.
    Seorang mahasiswa diprediksi paling cocok berkarir sebagai: {predicted_career}.

    Keterampilan yang dia miliki saat ini: {user_skills}
    Tools yang dia kuasai: {user_tools}

    Tugasmu:
    Buatkan roadmap belajar taktis berisi 3 langkah (bullet points) untuk mencapai karir {predicted_career}
    tersebut, bertolak dari skill yang dia miliki.

    Aturan:
    - Gunakan bahasa Indonesia yang ramah dan memotivasi.
    - Format langsung menggunakan bullet points.
    - Panjang maksimal 150-200 kata.
    """
    try:
        response = gemini_model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Gagal menghasilkan roadmap: {str(e)}"

def get_career_recommendation(payload):
    """
    Fungsi utama yang dipanggil oleh endpoint API Backend.
    """
    # Sanitasi Input (Proteksi fitur yang kosong agar tidak NaN)
    for field in ['all_skills', 'tools', 'databases']:
        if not payload.get(field) or str(payload[field]).strip() == "":
            payload[field] = "none"

    years_code = float(payload.get('years_code', 0.0))
    edu_level = float(payload.get('education_level', 0.0))

    # Format input sesuai kebutuhan Multi-Input model Keras
    input_data = {
        'years_code': np.array([years_code]),
        'education_level': np.array([edu_level]),
        'all_skills': np.array([payload['all_skills']]),
        'tools': np.array([payload['tools']]),
        'databases': np.array([payload['databases']])
    }

    # Prediksi
    predictions = recsys_model.predict(input_data, verbose=0)[0]

    # Ambil Top 3
    top_3_indices = predictions.argsort()[-3:][::-1]
    results = []
    for idx in top_3_indices:
        results.append({
            "career": CAREER_LABELS[idx],
            "score": round(float(predictions[idx]) * 100, 1)
        })

    top_1_career = results[0]['career']

    # Generate Roadmap dengan Gemini
    roadmap = generate_roadmap(
        top_1_career,
        payload['all_skills'],
        payload['tools']
    )

    return {
        "top_recommendations": results,
        "ai_roadmap": roadmap
    }